(ns game.data)

(defonce PLAYER (atom nil))
(defonce INPUT (atom nil))
(defonce CAMERA (atom nil))
(defonce CAMERA-AXIS (atom nil))
(defonce AIM (atom nil))
(defonce MENU (atom nil))
(defonce SWAPPED (atom nil))
(defonce SIZE (atom 0))